/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StaffRouteImport } from './routes/_staff'
import { Route as StaffIndexRouteImport } from './routes/_staff/index'
import { Route as StaffSettingsRouteImport } from './routes/_staff/settings'
import { Route as StaffReportsRouteImport } from './routes/_staff/reports'
import { Route as StaffQueueRouteImport } from './routes/_staff/queue'
import { Route as StaffCommentsRouteImport } from './routes/_staff/comments'
import { Route as StaffCategoriesRouteImport } from './routes/_staff/categories'
import { Route as StaffAuditRouteImport } from './routes/_staff/audit'
import { Route as StaffUsersIndexRouteImport } from './routes/_staff/users.index'
import { Route as StaffProjectsIndexRouteImport } from './routes/_staff/projects.index'
import { Route as StaffUsersIdRouteImport } from './routes/_staff/users.$id'
import { Route as StaffProjectsIdRouteImport } from './routes/_staff/projects.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StaffRoute,
} as any)
const StaffReportsRoute = StaffReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => StaffRoute,
} as any)
const StaffQueueRoute = StaffQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCommentsRoute = StaffCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCategoriesRoute = StaffCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAuditRoute = StaffAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => StaffRoute,
} as any)
const StaffUsersIndexRoute = StaffUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProjectsIndexRoute = StaffProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffUsersIdRoute = StaffUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProjectsIdRoute = StaffProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/audit': typeof StaffAuditRoute
  '/categories': typeof StaffCategoriesRoute
  '/comments': typeof StaffCommentsRoute
  '/queue': typeof StaffQueueRoute
  '/reports': typeof StaffReportsRoute
  '/settings': typeof StaffSettingsRoute
  '/': typeof StaffIndexRoute
  '/projects/$id': typeof StaffProjectsIdRoute
  '/users/$id': typeof StaffUsersIdRoute
  '/projects': typeof StaffProjectsIndexRoute
  '/users': typeof StaffUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof StaffAuditRoute
  '/categories': typeof StaffCategoriesRoute
  '/comments': typeof StaffCommentsRoute
  '/queue': typeof StaffQueueRoute
  '/reports': typeof StaffReportsRoute
  '/settings': typeof StaffSettingsRoute
  '/': typeof StaffIndexRoute
  '/projects/$id': typeof StaffProjectsIdRoute
  '/users/$id': typeof StaffUsersIdRoute
  '/projects': typeof StaffProjectsIndexRoute
  '/users': typeof StaffUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_staff': typeof StaffRouteWithChildren
  '/login': typeof LoginRoute
  '/_staff/audit': typeof StaffAuditRoute
  '/_staff/categories': typeof StaffCategoriesRoute
  '/_staff/comments': typeof StaffCommentsRoute
  '/_staff/queue': typeof StaffQueueRoute
  '/_staff/reports': typeof StaffReportsRoute
  '/_staff/settings': typeof StaffSettingsRoute
  '/_staff/': typeof StaffIndexRoute
  '/_staff/projects/$id': typeof StaffProjectsIdRoute
  '/_staff/users/$id': typeof StaffUsersIdRoute
  '/_staff/projects/': typeof StaffProjectsIndexRoute
  '/_staff/users/': typeof StaffUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/audit'
    | '/categories'
    | '/comments'
    | '/queue'
    | '/reports'
    | '/settings'
    | '/'
    | '/projects/$id'
    | '/users/$id'
    | '/projects'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/categories'
    | '/comments'
    | '/queue'
    | '/reports'
    | '/settings'
    | '/'
    | '/projects/$id'
    | '/users/$id'
    | '/projects'
    | '/users'
  id:
    | '__root__'
    | '/_staff'
    | '/login'
    | '/_staff/audit'
    | '/_staff/categories'
    | '/_staff/comments'
    | '/_staff/queue'
    | '/_staff/reports'
    | '/_staff/settings'
    | '/_staff/'
    | '/_staff/projects/$id'
    | '/_staff/users/$id'
    | '/_staff/projects/'
    | '/_staff/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StaffRoute: typeof StaffRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff/': {
      id: '/_staff/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/settings': {
      id: '/_staff/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/reports': {
      id: '/_staff/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof StaffReportsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/queue': {
      id: '/_staff/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof StaffQueueRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/comments': {
      id: '/_staff/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof StaffCommentsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/categories': {
      id: '/_staff/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof StaffCategoriesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/audit': {
      id: '/_staff/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof StaffAuditRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/users/': {
      id: '/_staff/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof StaffUsersIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/projects/': {
      id: '/_staff/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof StaffProjectsIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/users/$id': {
      id: '/_staff/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof StaffUsersIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/projects/$id': {
      id: '/_staff/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof StaffProjectsIdRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface StaffRouteChildren {
  StaffAuditRoute: typeof StaffAuditRoute
  StaffCategoriesRoute: typeof StaffCategoriesRoute
  StaffCommentsRoute: typeof StaffCommentsRoute
  StaffQueueRoute: typeof StaffQueueRoute
  StaffReportsRoute: typeof StaffReportsRoute
  StaffSettingsRoute: typeof StaffSettingsRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffProjectsIdRoute: typeof StaffProjectsIdRoute
  StaffUsersIdRoute: typeof StaffUsersIdRoute
  StaffProjectsIndexRoute: typeof StaffProjectsIndexRoute
  StaffUsersIndexRoute: typeof StaffUsersIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAuditRoute: StaffAuditRoute,
  StaffCategoriesRoute: StaffCategoriesRoute,
  StaffCommentsRoute: StaffCommentsRoute,
  StaffQueueRoute: StaffQueueRoute,
  StaffReportsRoute: StaffReportsRoute,
  StaffSettingsRoute: StaffSettingsRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffProjectsIdRoute: StaffProjectsIdRoute,
  StaffUsersIdRoute: StaffUsersIdRoute,
  StaffProjectsIndexRoute: StaffProjectsIndexRoute,
  StaffUsersIndexRoute: StaffUsersIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StaffRoute: StaffRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
