/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedDashboardRouteRouteImport } from './routes/_authed/dashboard/route'
import { Route as AuthedDashboardProjectsRouteImport } from './routes/_authed/dashboard/projects'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRouteRoute = AuthedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardProjectsRoute = AuthedDashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/dashboard/projects': typeof AuthedDashboardProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/dashboard/projects': typeof AuthedDashboardProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/_authed/dashboard/projects': typeof AuthedDashboardProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in/$'
    | '/dashboard/projects'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/onboarding' | '/sign-in/$' | '/dashboard/projects'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/_authed/onboarding'
    | '/sign-in/$'
    | '/_authed/dashboard/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/projects': {
      id: '/_authed/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof AuthedDashboardProjectsRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
  }
}

interface AuthedDashboardRouteRouteChildren {
  AuthedDashboardProjectsRoute: typeof AuthedDashboardProjectsRoute
}

const AuthedDashboardRouteRouteChildren: AuthedDashboardRouteRouteChildren = {
  AuthedDashboardProjectsRoute: AuthedDashboardProjectsRoute,
}

const AuthedDashboardRouteRouteWithChildren =
  AuthedDashboardRouteRoute._addFileChildren(AuthedDashboardRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRouteRoute: typeof AuthedDashboardRouteRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRouteRoute: AuthedDashboardRouteRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
