/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AuthedDashboardRouteRouteImport } from './routes/_authed/dashboard/route'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as MakersHandleRouteImport } from './routes/makers/$handle'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as RankingsWeekRouteImport } from './routes/rankings/$week'
import { Route as AuthedDashboardProfileRouteImport } from './routes/_authed/dashboard/profile'
import { Route as AuthedDashboardReleasesRouteImport } from './routes/_authed/dashboard/releases'
import { Route as AuthedDashboardSubmitRouteImport } from './routes/_authed/dashboard/submit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRouteRoute = AuthedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const MakersHandleRoute = MakersHandleRouteImport.update({
  id: '/makers/$handle',
  path: '/makers/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsWeekRoute = RankingsWeekRouteImport.update({
  id: '/rankings/$week',
  path: '/rankings/$week',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardProfileRoute = AuthedDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardReleasesRoute = AuthedDashboardReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardSubmitRoute = AuthedDashboardSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/makers/$handle': typeof MakersHandleRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/rankings/$week': typeof RankingsWeekRoute
  '/dashboard/profile': typeof AuthedDashboardProfileRoute
  '/dashboard/releases': typeof AuthedDashboardReleasesRoute
  '/dashboard/submit': typeof AuthedDashboardSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/makers/$handle': typeof MakersHandleRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/rankings/$week': typeof RankingsWeekRoute
  '/dashboard/profile': typeof AuthedDashboardProfileRoute
  '/dashboard/releases': typeof AuthedDashboardReleasesRoute
  '/dashboard/submit': typeof AuthedDashboardSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/makers/$handle': typeof MakersHandleRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/rankings/$week': typeof RankingsWeekRoute
  '/_authed/dashboard/profile': typeof AuthedDashboardProfileRoute
  '/_authed/dashboard/releases': typeof AuthedDashboardReleasesRoute
  '/_authed/dashboard/submit': typeof AuthedDashboardSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/onboarding'
    | '/makers/$handle'
    | '/projects/$slug'
    | '/rankings/$week'
    | '/dashboard/profile'
    | '/dashboard/releases'
    | '/dashboard/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/onboarding'
    | '/makers/$handle'
    | '/projects/$slug'
    | '/rankings/$week'
    | '/dashboard/profile'
    | '/dashboard/releases'
    | '/dashboard/submit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/dashboard'
    | '/_authed/onboarding'
    | '/makers/$handle'
    | '/projects/$slug'
    | '/rankings/$week'
    | '/_authed/dashboard/profile'
    | '/_authed/dashboard/releases'
    | '/_authed/dashboard/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  MakersHandleRoute: typeof MakersHandleRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  RankingsWeekRoute: typeof RankingsWeekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/makers/$handle': {
      id: '/makers/$handle'
      path: '/makers/$handle'
      fullPath: '/makers/$handle'
      preLoaderRoute: typeof MakersHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/$week': {
      id: '/rankings/$week'
      path: '/rankings/$week'
      fullPath: '/rankings/$week'
      preLoaderRoute: typeof RankingsWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/profile': {
      id: '/_authed/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthedDashboardProfileRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/releases': {
      id: '/_authed/dashboard/releases'
      path: '/releases'
      fullPath: '/dashboard/releases'
      preLoaderRoute: typeof AuthedDashboardReleasesRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/submit': {
      id: '/_authed/dashboard/submit'
      path: '/submit'
      fullPath: '/dashboard/submit'
      preLoaderRoute: typeof AuthedDashboardSubmitRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
  }
}

interface AuthedDashboardRouteRouteChildren {
  AuthedDashboardProfileRoute: typeof AuthedDashboardProfileRoute
  AuthedDashboardReleasesRoute: typeof AuthedDashboardReleasesRoute
  AuthedDashboardSubmitRoute: typeof AuthedDashboardSubmitRoute
}

const AuthedDashboardRouteRouteChildren: AuthedDashboardRouteRouteChildren = {
  AuthedDashboardProfileRoute: AuthedDashboardProfileRoute,
  AuthedDashboardReleasesRoute: AuthedDashboardReleasesRoute,
  AuthedDashboardSubmitRoute: AuthedDashboardSubmitRoute,
}

const AuthedDashboardRouteRouteWithChildren =
  AuthedDashboardRouteRoute._addFileChildren(AuthedDashboardRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRouteRoute: typeof AuthedDashboardRouteRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRouteRoute: AuthedDashboardRouteRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  MakersHandleRoute: MakersHandleRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  RankingsWeekRoute: RankingsWeekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
